import { createSlice, PayloadAction } from "@reduxjs/toolkit";

import { Product } from "../../types";
import { Descriptions, Images, Titles } from "./placeholders";

const initialState: Record<Product["id"], Product> = {
  "40e3fe57": {
    article: "40e3fe57",
    description: Descriptions.HelicopterTour,
    estimation: 90,
    favorites: false,
    id: "40e3fe57",
    images: [Images.HelicopterTour, Images.HelicopterTour, Images.HelicopterTour, Images.HelicopterTour],
    inStock: 12,
    price: 10_000,
    reviews: 200,
    soldTimes: 15,
    title: Titles.HelicopterTour,
  },
  "46d36fa2": {
    article: "46d36fa2",
    description: Descriptions.WeddingSalon,
    estimation: 90,
    favorites: true,
    id: "46d36fa2",
    images: [Images.WeddingSalon],
    inStock: 12,
    price: 14_750,
    reviews: 200,
    soldTimes: 18,
    title: Titles.WeddingSalon,
  },
  "962d651a": {
    article: "962d651a",
    description: Descriptions.StainedGlass,
    estimation: 90,
    favorites: false,
    id: "962d651a",
    images: [Images.StainedGlass],
    inStock: 12,
    price: 2300,
    reviews: 200,
    soldTimes: 125,
    title: Titles.StainedGlass,
  },
  "99720f1a": {
    article: "99720f1a",
    description: Descriptions.WindForest,
    estimation: 99,
    favorites: false,
    id: "99720f1a",
    images: [Images.WindForest],
    inStock: 12,
    price: 500,
    reviews: 200,
    soldTimes: 12,
    title: Titles.WindForest,
  },
  "99720f2a": {
    article: "99720f2a",
    description: Descriptions.Taxi,
    estimation: 90,
    favorites: false,
    id: "99720f2a",
    images: [Images.Taxi],
    inStock: 12,
    price: 350,
    reviews: 200,
    soldTimes: 13,
    title: Titles.Taxi,
  },
  "12699858": {
    article: "12699858",
    description: Descriptions.AutumnPantsuit,
    estimation: 90,
    favorites: false,
    id: "12699858",
    images: [Images.AutumnPantsuit],
    inStock: 12,
    price: 1800,
    reviews: 200,
    soldTimes: 45,
    title: Titles.AutumnPantsuit,
  },
  b7969abe: {
    article: "b7969abe",
    description: Descriptions.CreatingAdvertisingPosters,
    estimation: 90,
    favorites: true,
    id: "b7969abe",
    images: [Images.CreatingAdvertisingPosters],
    inStock: 12,
    price: 240,
    reviews: 200,
    soldTimes: 5,
    title: Titles.CreatingAdvertisingPosters,
  },
  d1149932: {
    article: "d1149932",
    description: Descriptions.AsphaltAndConcrete,
    estimation: 90,
    favorites: true,
    id: "d1149932",
    images: [Images.AsphaltAndConcrete],
    inStock: 12,
    price: 3600,
    reviews: 200,
    soldTimes: 1,
    title: Titles.AsphaltAndConcrete,
  },
};

const productsSlice = createSlice({
  initialState,
  name: "products",
  reducers: {
    toggleFavorite: (state, { payload }: PayloadAction<{ productId: Product["id"] }>) => {
      state[payload.productId].favorites = !state[payload.productId].favorites;
    },
  },
});

export default productsSlice;
