const localization = {
  aboutMe: "О себе",
  article: "артикул",
  cancel: "отмена",
  chooseAll: "Выбрать всё",
  copied: "Скопировано",
  copyMessageToOrder: "Скопируйте сообщение для заказа",
  description: "Описание",
  emptyShoppingList: "ваша корзина пуста",
  firstname: "Имя",
  inStock: "В наличии",
  labels: "Метки",
  lastname: "Фамилия",
  login: "Войти",
  next: "далее",
  order: "Заказать",
  orderMessageStart: "Привет, хочу купить эти товары",
  perUnit: "за 1 шт.",
  products: "товаров",
  productWasDeletedFromShoppingList: "Товар удалён из корзины",
  psc: "шт.",
  registration: "Регистрация",
  security: "Безопасность",
  shop: "Магазин",
  shoppingList: "Корзина",
  siteTree: "Дерево сайта",
  sizeImage: (size: number) => `Размер файла должен быть не более ${size} Mб`,
  startShopping: "Начать покупки",
  toShoppingList: "В корзину",
  totalCostOmitDelivery: "Стоимость без доставки",
  welcome: "Добро пожаловать в магазин",
};

export default localization;
