const localization = {
  article: "артикул",
  cancel: "отмена",
  chooseAll: "Выбрать всё",
  copied: "Скопировано",
  copyMessageToOrder: "Скопируйте сообщение для заказа",
  description: "Описание",
  emptyShoppingList: "ваша корзина пуста",
  inStock: "В наличии",
  labels: "Метки",
  order: "Заказать",
  orderMessageStart: "Привет, хочу купить эти товары",
  perUnit: "за 1 шт.",
  products: "товаров",
  productWasDeletedFromShoppingList: "Товар удалён из корзины",
  psc: "шт.",
  shop: "Магазин",
  shoppingList: "Корзина",
  siteTree: "Дерево сайта",
  startShopping: "Начать покупки",
  toShoppingList: "В корзину",
  totalCostOmitDelivery: "Стоимость без доставки",
  welcome: "Добро пожаловать в магазин",
};

export default localization;
